# Generated by Django 2.1.5 on 2019-02-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Twitts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_avatar', models.URLField()),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('text', models.CharField(max_length=500)),
                ('media', models.URLField()),
                ('twit_raw_link', models.URLField()),
                ('retweet_count', models.PositiveIntegerField()),
                ('likes_count', models.PositiveIntegerField()),
            ],
        ),
    ]
